version: "3.8"

services:
  db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=password123
      - MYSQL_DATABASE=dbproject
    ports:
      - "3306:3306"
    restart: on-failure
    networks:
      - network
  api:
    image: projet-api
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: on-failure
    networks:
      - network
networks:
  network: