version: "3"

services:
  db-mysql:
    image: mysql:latest
    container_name: db-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password123
      - MYSQL_DATABASE=dbproject
    ports:
      - "3306:3306"
  ecommerce-api:
    container_name: ecommerce-api
    build:
      context: projet
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    links:
      - db-mysql
    restart: on-failure
  angular-ui:
    container_name: angular-ui
    build:
      context: projet-web
      dockerfile: Dockerfile
    ports:
      - "80:80"
    links:
      - ecommerce-api