version: "3.8"

services:
  db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=password123
      - MYSQL_DATABASE=dbproject
    ports:
      - "3306:3306"
    restart: on-failure
    networks:
      - network
  api:
    image: projet-api
    container_name: api
    build:
      context: projet
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: on-failure
    networks:
      - network
  web:
    image: web-api
    container_name: web-api
    build:
      context: projet-web
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - network
networks:
  network: